### ISSUE TITLE
не войти в акк

### ISSUE THREAD

**Issue by gladiator812** [zxcloli666/SoundCloud-Desktop#8]
![Screenshot_2](https://github.com/user-attachments/assets/d7880807-23f9-4411-a631-e48235dde9d3)
такая тема выползает когда пытаюсь войти в свой акк

**Comment by zxcloli666** [comment]
Привет.
Внес некоторые корректировки в прокси.
Проверь, работает ли.

**Comment by gladiator812** [comment]
> Привет. Внес некоторые корректировки в прокси. Проверь, работает ли.

Да все работает теперь, можешь еще сделать чтобы была активность в дискорде что я слушаю

**Comment by zxcloli666** [comment]
Отлично!

Активность дискорда в планах, но когда сделаю не знаю.
Напишу об этом в #3, когда сделаю
